# Site settings
title: The Fuel
email: scot@gooffroad.co
description: >
  The Fuel's Writer-In-Residence programs trains people 
  inside prisons and jails to use the power of the pen as a pathway to success.
baseurl: ""
url: "https://www.the-fuel.com" # the base hostname & protocol for your site
image_path: '/assets/img'

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['_sass', '_src', '_grunt', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'Gemfile', 'build.sh']

# Enabling gems
plugins: [
"jekyll-contentful"
]

defaults:
  -
    scope:
      type: "posts"
    values: 
      layout: "post"
      permalink: /blog/:title

contentful:
  preview: No 
  production_access_token: ed7b8f79a95864735f8b842b475bdb379c42ca92f45dc318994daec6e9000a26
  preview_access_token: 5f2d29a358c334582834eecfdc20a1cc0e40b16cf8c812f46c81b8bf1d1822df
  space: jo6vhcg97vhs
  content_types:
   - "story"
  spaces:
    - proddata: # Jekyll _data folder identifier - Required
        space: jo6vhcg97vhs        # Required
        access_token: ed7b8f79a95864735f8b842b475bdb379c42ca92f45dc318994daec6e9000a26 # Required
        cda_query:                 # Optional
          include: 2
          limit: 300
        content_types:             # Optional
         cat: story
 
