---
quote:
- sys:
    id: 2ar6tig7peOssSs88Y44kG
  quoteText: quote 1
  author: Dalai Lama
  authorTitle: Monk
  picture:
    title: blank-profile-picture-973460 1280
    description: 
    url: //images.contentful.com/jo6vhcg97vhs/5i7nn5Fyp20Qscwo4c8qQE/f9566c836c06e39ad44be5b3dbfc1c1d/blank-profile-picture-973460_1280.png
webPagesContent:
- sys:
    id: 1zJKPT9nK4kyYiO8ygeYCE
  aboutPageYoutubeVideoId: Lorem ipsum
  aboutUsHeader: Lorem ipsum
  aboutUsOurMission: "America’s taxpayer-funded boondoggle of a criminal justice system
    is bankrupt. Tasked with rehabilitation, the industrialized prison economy now
    locks up more people than any other nation. Of those younger than 25, 84 percent
    will return to prison after release. A $75 billion a year price tag has failed
    to reduce recidivism rates that have crippled our country. What will move the
    needle? An all-of-the-above strategy that starts with fueling reform through the
    power of story. We’re driving change. Ride with us. \n"
  teachingEntrepreneurshipInPrison: Lorem ipsum
partnerLogo:
- sys:
    id: 59G3FhS2UUsG4UsWESuAu2
  name: test
  partnerLogo:
    title: blank-profile-picture-973460 1280
    description: 
    url: //images.contentful.com/jo6vhcg97vhs/5i7nn5Fyp20Qscwo4c8qQE/f9566c836c06e39ad44be5b3dbfc1c1d/blank-profile-picture-973460_1280.png
  order: 0
story:
- sys:
    id: 1HSJUMdGJW2mkWqmqoQSuy
  title: Story 1
  subtitle: Super Story
  author: Dalai Lama
  isFirstStoryOnFrontPage: true
  isTopStory: true
  heroImage:
    title: blank-profile-picture-973460 1280
    description: 
    url: //images.contentful.com/jo6vhcg97vhs/5i7nn5Fyp20Qscwo4c8qQE/f9566c836c06e39ad44be5b3dbfc1c1d/blank-profile-picture-973460_1280.png
  contentAboveNewsletter: Lorem ipsum
  factBox: Lorem ipsum
  contentBelowNewsletter: Lorem ipsum
pitCrew:
- sys:
    id: 3WYkcfIAXm008qIycuQa4E
  name: Pit Crew 1
  title: Pit Crew
  order: 0
  picture:
    title: blank-profile-picture-973460 1280
    description: 
    url: //images.contentful.com/jo6vhcg97vhs/5i7nn5Fyp20Qscwo4c8qQE/f9566c836c06e39ad44be5b3dbfc1c1d/blank-profile-picture-973460_1280.png
  bio: Lorem ipsum
writersInResidence:
- sys:
    id: 4C1NI9N1dKUyaMkKUWK4o8
  name: Writer 1
  title: writer
  order: 0
  picture:
    title: blank-profile-picture-973460 1280
    description: 
    url: //images.contentful.com/jo6vhcg97vhs/5i7nn5Fyp20Qscwo4c8qQE/f9566c836c06e39ad44be5b3dbfc1c1d/blank-profile-picture-973460_1280.png
